CREATE TABLE `order_info` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
  `order_code` varchar(45) NOT NULL COMMENT '订单号',
  `order_type` varchar(15) NOT NULL COMMENT '订单类型',
  `deleted` varchar(15) NOT NULL COMMENT '逻辑删除，T/F',
  `create_by` varchar(45) NOT NULL COMMENT '创建人',
  `modify_by` varchar(45) NOT NULL COMMENT '修改人',
  `create_time` datetime(3) NOT NULL COMMENT '创建时间',
  `modify_time` datetime(3) NOT NULL COMMENT '修改时间',
  `extend_field` varchar(45) DEFAULT NULL COMMENT '拓展字段',
  PRIMARY KEY (`id`)
);
CREATE TABLE `pay_tc_trade` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
  `trade_no` varchar(64) NOT NULL COMMENT '交易单号',
  `main_event_no` varchar(64) COMMENT '主事件单号',
  `out_trade_no` varchar(64) NOT NULL COMMENT '外部交易单号',
  `sub_out_trade_no` varchar(64) COMMENT '外部交易子单号',
  `biz_prod` varchar(16) NOT NULL COMMENT '产品码，第一码',
  `biz_mode` varchar(16) NOT NULL COMMENT '业务模式码，第二码',
  `trade_type` varchar(16) NOT NULL COMMENT '交易类型',
  `state` varchar(16) NOT NULL COMMENT '交易状态',
  `settle_state` varchar(16) NOT NULL COMMENT '结算状态',
  `total_amount` bigint NOT NULL DEFAULT 0 COMMENT '交易总金额',
  `pay_amount` bigint NOT NULL DEFAULT 0 COMMENT '支付总金额',
  `refund_amount` bigint NOT NULL DEFAULT 0 COMMENT '退款总金额',
  `refunding_amount` bigint NOT NULL DEFAULT 0 COMMENT '退款中金额',
  `settle_amount` bigint NOT NULL DEFAULT 0 COMMENT '结算总金额',
  `settling_amount` bigint NOT NULL DEFAULT 0 COMMENT '结算中金额',
  `shared_amount` bigint NOT NULL DEFAULT 0 COMMENT '分账总金额',
  `sharing_amount` bigint NOT NULL DEFAULT 0 COMMENT '分账中金额',
  `refund_shared_amount` bigint NOT NULL DEFAULT 0 COMMENT '退分账总金额',
  `refund_sharing_amount` bigint NOT NULL DEFAULT 0 COMMENT '退分账中金额',
  `currency` varchar(16) NOT NULL COMMENT '交易币种',
  `partner_id` varchar(32) NOT NULL COMMENT '合作方',
  `payee_id` varchar(64) NOT NULL COMMENT '收款方',
  `payer_id` varchar(64) NOT NULL COMMENT '付款方',
  `settle_time` datetime(3) DEFAULT NULL COMMENT '结算时间',
  `close_time` datetime(3) DEFAULT NULL COMMENT '关单时间',
  `expire_time` datetime(3) NOT NULL COMMENT '过期时间',
  `env` varchar(16) NOT NULL COMMENT '环境',
  `tags` varchar(512) DEFAULT NULL COMMENT '业务标记',
  `create_time` datetime(3) NOT NULL COMMENT '创建时间',
  `modify_time` datetime(3) NOT NULL COMMENT '修改时间',
  `extend_field` varchar(2048) DEFAULT NULL COMMENT '拓展字段',
  `attachment` varchar(2048) DEFAULT NULL COMMENT '业务透传字段',
  PRIMARY KEY (`id`)
);

CREATE TABLE `pay_tc_trade_event` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
  `trade_event_no` varchar(64) NOT NULL COMMENT '事件单号',
  `trade_no` varchar(64) NOT NULL COMMENT '交易单号',
  `out_biz_no` varchar(64) NOT NULL COMMENT '外部业务单号',
  `out_trade_no` varchar(64) NOT NULL COMMENT '外部交易单号',
  `state` varchar(16) NOT NULL COMMENT '事件状态',
  `biz_type` varchar(16) NOT NULL COMMENT '业务类型',
  `biz_action` varchar(16) NOT NULL COMMENT '业务流向码，第三码',
  `total_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '交易总金额',
  `real_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '实际金额',
  `revert_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '逆向总金额',
  `reverting_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '逆向中金额',
  `event_type` varchar(16) NOT NULL COMMENT '事件类型',
  `relation_no` varchar(64) DEFAULT NULL COMMENT '关联单号',
  `currency` varchar(16) NOT NULL COMMENT '交易币种',
  `partner_id` varchar(32) NOT NULL COMMENT '合作方',
  `payee_id` varchar(64) NOT NULL COMMENT '收款方',
  `payer_id` varchar(64) NOT NULL COMMENT '付款方',
  `finished_time` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `close_time` datetime(3) DEFAULT NULL COMMENT '关单时间',
  `expire_time` datetime(3) NOT NULL COMMENT '过期时间',
  `env` varchar(16) NOT NULL COMMENT '环境',
  `tags` varchar(512) DEFAULT NULL COMMENT '业务标记',
  `create_time` datetime(3) NOT NULL COMMENT '创建时间',
  `modify_time` datetime(3) NOT NULL COMMENT '修改时间',
  `extend_field` varchar(2048) DEFAULT NULL COMMENT '拓展字段',
  `attachment` varchar(2048) DEFAULT NULL COMMENT '业务透传字段',
  PRIMARY KEY (`id`)
);
CREATE TABLE `pay_pc_payment_contract` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
  `payment_no` varchar(64) NOT NULL COMMENT '支付单号',
  `trade_no` varchar(64) NOT NULL COMMENT '交易单号',
  `trade_event_no` varchar(64) NOT NULL COMMENT '交易事件单号',
  `out_trade_no` varchar(64) NOT NULL COMMENT '外部交易单号',
  `relation_no` varchar(64) DEFAULT NULL COMMENT '关联单号',
  `state` varchar(16) NOT NULL COMMENT '事件状态',
  `biz_type` varchar(16) DEFAULT NULL COMMENT '业务类型',
  `biz_action` varchar(16) NOT NULL COMMENT '业务流向码，第三码',
  `pay_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '支付金额',
  `currency` varchar(16) NOT NULL COMMENT '交易币种',
  `finished_time` datetime(3) DEFAULT NULL COMMENT '支付完成时间',
  `env` varchar(16) NOT NULL COMMENT '环境',
  `tags` varchar(512) DEFAULT NULL COMMENT '业务标记',
  `create_time` datetime(3) NOT NULL COMMENT '创建时间',
  `modify_time` datetime(3) NOT NULL COMMENT '修改时间',
  `extend_field` varchar(2048) DEFAULT NULL COMMENT '拓展字段',
  `attachment` varchar(2048) DEFAULT NULL COMMENT '业务透传字段',
  PRIMARY KEY (`id`)
);
CREATE TABLE `pay_pc_payment_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
  `payment_no` varchar(64) NOT NULL COMMENT '支付单号',
  `payment_detail_no` varchar(64) NOT NULL COMMENT '支付明细单号',
  `trade_no` varchar(64) NOT NULL COMMENT '交易单号',
  `trade_event_no` varchar(64) NOT NULL COMMENT '交易事件单号',
  `state` varchar(16) NOT NULL COMMENT '事件状态，0:初始化，1:支付提交，2:支付中,3:预支付成功，4:支付成功，5：支付失败，6：支付关闭',
  `pay_channel_api` varchar(16) NOT NULL COMMENT '支付工具',
  `amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '支付金额',
  `refund_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '退款金额',
  `currency` varchar(16) NOT NULL COMMENT '交易币种',
  `partner_id` varchar(32) NOT NULL COMMENT '合作方',
  `payee_id` varchar(64) NOT NULL COMMENT '收款方',
  `payer_id` varchar(64) NOT NULL COMMENT '付款方',
  `finished_time` datetime(3) DEFAULT NULL COMMENT '支付完成时间',
  `expire_time` datetime(3) NOT NULL COMMENT '过期时间',
  `channel_no` varchar(64) DEFAULT NULL COMMENT '渠道单号',
  `env` varchar(16) NOT NULL COMMENT '环境',
  `tags` varchar(512) DEFAULT NULL COMMENT '业务标记',
  `create_time` datetime(3) NOT NULL COMMENT '创建时间',
  `modify_time` datetime(3) NOT NULL COMMENT '修改时间',
  `extend_field` varchar(2048) DEFAULT NULL COMMENT '拓展字段',
  `attachment` varchar(2048) DEFAULT NULL COMMENT '业务透传字段',
  PRIMARY KEY (`id`)
);